<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('voices', function (Blueprint $table) {
            $table->id();
            $table->string('name', 127);
            $table->string('short_name', 63);
            $table->enum('gender', ['Male', 'Female', 'Neutral']);
            $table->boolean('is_favorite')->default(false);
            $table->timestamps();
        });

        $raw_insert = "(2, 'Adri', 'af-ZA-AdriNeural', 'Female', 0),
                        (3, 'Willem', 'af-ZA-WillemNeural', 'Male', 0),
                        (4, 'Mekdes', 'am-ET-MekdesNeural', 'Female', 0),
                        (5, 'Ameha', 'am-ET-AmehaNeural', 'Male', 0),
                        (6, 'Fatima', 'ar-AE-FatimaNeural', 'Female', 0),
                        (7, 'Hamdan', 'ar-AE-HamdanNeural', 'Male', 0),
                        (8, 'Laila', 'ar-BH-LailaNeural', 'Female', 0),
                        (9, 'Ali', 'ar-BH-AliNeural', 'Male', 0),
                        (10, 'Amina', 'ar-DZ-AminaNeural', 'Female', 0),
                        (11, 'Ismael', 'ar-DZ-IsmaelNeural', 'Male', 0),
                        (12, 'Salma', 'ar-EG-SalmaNeural', 'Female', 0),
                        (13, 'Shakir', 'ar-EG-ShakirNeural', 'Male', 0),
                        (14, 'Rana', 'ar-IQ-RanaNeural', 'Female', 0),
                        (15, 'Bassel', 'ar-IQ-BasselNeural', 'Male', 0),
                        (16, 'Sana', 'ar-JO-SanaNeural', 'Female', 0),
                        (17, 'Taim', 'ar-JO-TaimNeural', 'Male', 0),
                        (18, 'Noura', 'ar-KW-NouraNeural', 'Female', 0),
                        (19, 'Fahed', 'ar-KW-FahedNeural', 'Male', 0),
                        (20, 'Layla', 'ar-LB-LaylaNeural', 'Female', 0),
                        (21, 'Rami', 'ar-LB-RamiNeural', 'Male', 0),
                        (22, 'Iman', 'ar-LY-ImanNeural', 'Female', 0),
                        (23, 'Omar', 'ar-LY-OmarNeural', 'Male', 0),
                        (24, 'Mouna', 'ar-MA-MounaNeural', 'Female', 0),
                        (25, 'Jamal', 'ar-MA-JamalNeural', 'Male', 0),
                        (26, 'Aysha', 'ar-OM-AyshaNeural', 'Female', 0),
                        (27, 'Abdullah', 'ar-OM-AbdullahNeural', 'Male', 0),
                        (28, 'Amal', 'ar-QA-AmalNeural', 'Female', 0),
                        (29, 'Moaz', 'ar-QA-MoazNeural', 'Male', 0),
                        (30, 'Zariyah', 'ar-SA-ZariyahNeural', 'Female', 0),
                        (31, 'Hamed', 'ar-SA-HamedNeural', 'Male', 0),
                        (32, 'Amany', 'ar-SY-AmanyNeural', 'Female', 0),
                        (33, 'Laith', 'ar-SY-LaithNeural', 'Male', 0),
                        (34, 'Reem', 'ar-TN-ReemNeural', 'Female', 0),
                        (35, 'Hedi', 'ar-TN-HediNeural', 'Male', 0),
                        (36, 'Maryam', 'ar-YE-MaryamNeural', 'Female', 0),
                        (37, 'Saleh', 'ar-YE-SalehNeural', 'Male', 0),
                        (38, 'Yashica', 'as-IN-YashicaNeural', 'Female', 0),
                        (39, 'Priyom', 'as-IN-PriyomNeural', 'Male', 0),
                        (40, 'Banu', 'az-AZ-BanuNeural', 'Female', 0),
                        (41, 'Babek', 'az-AZ-BabekNeural', 'Male', 0),
                        (42, 'Kalina', 'bg-BG-KalinaNeural', 'Female', 0),
                        (43, 'Borislav', 'bg-BG-BorislavNeural', 'Male', 0),
                        (44, 'Nabanita', 'bn-BD-NabanitaNeural', 'Female', 0),
                        (45, 'Pradeep', 'bn-BD-PradeepNeural', 'Male', 0),
                        (46, 'Tanishaa', 'bn-IN-TanishaaNeural', 'Female', 0),
                        (47, 'Bashkar', 'bn-IN-BashkarNeural', 'Male', 0),
                        (48, 'Vesna', 'bs-BA-VesnaNeural', 'Female', 0),
                        (49, 'Goran', 'bs-BA-GoranNeural', 'Male', 0),
                        (50, 'Joana', 'ca-ES-JoanaNeural', 'Female', 0),
                        (51, 'Enric', 'ca-ES-EnricNeural', 'Male', 0),
                        (52, 'Alba', 'ca-ES-AlbaNeural', 'Female', 0),
                        (53, 'Vlasta', 'cs-CZ-VlastaNeural', 'Female', 0),
                        (54, 'Antonin', 'cs-CZ-AntoninNeural', 'Male', 0),
                        (55, 'Nia', 'cy-GB-NiaNeural', 'Female', 0),
                        (56, 'Aled', 'cy-GB-AledNeural', 'Male', 0),
                        (57, 'Christel', 'da-DK-ChristelNeural', 'Female', 0),
                        (58, 'Jeppe', 'da-DK-JeppeNeural', 'Male', 0),
                        (59, 'Ingrid', 'de-AT-IngridNeural', 'Female', 0),
                        (60, 'Jonas', 'de-AT-JonasNeural', 'Male', 0),
                        (61, 'Leni', 'de-CH-LeniNeural', 'Female', 0),
                        (62, 'Jan', 'de-CH-JanNeural', 'Male', 0),
                        (63, 'Katja', 'de-DE-KatjaNeural', 'Female', 0),
                        (64, 'Conrad', 'de-DE-ConradNeural', 'Male', 0),
                        (65, 'Seraphina Multilingual', 'de-DE-SeraphinaMultilingualNeural', 'Female', 0),
                        (66, 'Florian Multilingual', 'de-DE-FlorianMultilingualNeural', 'Male', 0),
                        (67, 'Amala', 'de-DE-AmalaNeural', 'Female', 0),
                        (68, 'Bernd', 'de-DE-BerndNeural', 'Male', 0),
                        (69, 'Christoph', 'de-DE-ChristophNeural', 'Male', 0),
                        (70, 'Elke', 'de-DE-ElkeNeural', 'Female', 0),
                        (71, 'Gisela', 'de-DE-GiselaNeural', 'Female', 0),
                        (72, 'Kasper', 'de-DE-KasperNeural', 'Male', 0),
                        (73, 'Killian', 'de-DE-KillianNeural', 'Male', 0),
                        (74, 'Klarissa', 'de-DE-KlarissaNeural', 'Female', 0),
                        (75, 'Klaus', 'de-DE-KlausNeural', 'Male', 0),
                        (76, 'Louisa', 'de-DE-LouisaNeural', 'Female', 0),
                        (77, 'Maja', 'de-DE-MajaNeural', 'Female', 0),
                        (78, 'Ralf', 'de-DE-RalfNeural', 'Male', 0),
                        (79, 'Tanja', 'de-DE-TanjaNeural', 'Female', 0),
                        (80, 'Seraphina Dragon HD Latest', 'de-DE-Seraphina:DragonHDLatestNeural', 'Female', 0),
                        (81, 'Athina', 'el-GR-AthinaNeural', 'Female', 0),
                        (82, 'Nestoras', 'el-GR-NestorasNeural', 'Male', 0),
                        (83, 'Natasha', 'en-AU-NatashaNeural', 'Female', 0),
                        (84, 'William', 'en-AU-WilliamNeural', 'Male', 0),
                        (85, 'Annette', 'en-AU-AnnetteNeural', 'Female', 0),
                        (86, 'Carly', 'en-AU-CarlyNeural', 'Female', 0),
                        (87, 'Darren', 'en-AU-DarrenNeural', 'Male', 0),
                        (88, 'Duncan', 'en-AU-DuncanNeural', 'Male', 0),
                        (89, 'Elsie', 'en-AU-ElsieNeural', 'Female', 0),
                        (90, 'Freya', 'en-AU-FreyaNeural', 'Female', 0),
                        (91, 'Joanne', 'en-AU-JoanneNeural', 'Female', 0),
                        (92, 'Ken', 'en-AU-KenNeural', 'Male', 0),
                        (93, 'Kim', 'en-AU-KimNeural', 'Female', 0),
                        (94, 'Neil', 'en-AU-NeilNeural', 'Male', 0),
                        (95, 'Tim', 'en-AU-TimNeural', 'Male', 0),
                        (96, 'Tina', 'en-AU-TinaNeural', 'Female', 0),
                        (97, 'Clara', 'en-CA-ClaraNeural', 'Female', 0),
                        (98, 'Liam', 'en-CA-LiamNeural', 'Male', 0),
                        (99, 'Sonia', 'en-GB-SoniaNeural', 'Female', 0),
                        (100, 'Ryan', 'en-GB-RyanNeural', 'Male', 0),
                        (101, 'Libby', 'en-GB-LibbyNeural', 'Female', 0),
                        (102, 'Ada Multilingual', 'en-GB-AdaMultilingualNeural', 'Female', 0),
                        (103, 'Ollie Multilingual', 'en-GB-OllieMultilingualNeural', 'Male', 0),
                        (104, 'Abbi', 'en-GB-AbbiNeural', 'Female', 0),
                        (105, 'Alfie', 'en-GB-AlfieNeural', 'Male', 0),
                        (106, 'Bella', 'en-GB-BellaNeural', 'Female', 0),
                        (107, 'Elliot', 'en-GB-ElliotNeural', 'Male', 0),
                        (108, 'Ethan', 'en-GB-EthanNeural', 'Male', 0),
                        (109, 'Hollie', 'en-GB-HollieNeural', 'Female', 0),
                        (110, 'Maisie', 'en-GB-MaisieNeural', 'Female', 0),
                        (111, 'Noah', 'en-GB-NoahNeural', 'Male', 0),
                        (112, 'Oliver', 'en-GB-OliverNeural', 'Male', 0),
                        (113, 'Olivia', 'en-GB-OliviaNeural', 'Female', 0),
                        (114, 'Thomas', 'en-GB-ThomasNeural', 'Male', 0),
                        (115, 'Mia', 'en-GB-MiaNeural', 'Female', 0),
                        (116, 'Yan', 'en-HK-YanNeural', 'Female', 0),
                        (117, 'Sam', 'en-HK-SamNeural', 'Male', 0),
                        (118, 'Emily', 'en-IE-EmilyNeural', 'Female', 0),
                        (119, 'Connor', 'en-IE-ConnorNeural', 'Male', 0),
                        (120, 'Aarav', 'en-IN-AaravNeural', 'Male', 0),
                        (121, 'Aashi', 'en-IN-AashiNeural', 'Female', 0),
                        (122, 'Ananya', 'en-IN-AnanyaNeural', 'Female', 0),
                        (123, 'Kavya', 'en-IN-KavyaNeural', 'Female', 0),
                        (124, 'Kunal', 'en-IN-KunalNeural', 'Male', 0),
                        (125, 'Neerja', 'en-IN-NeerjaNeural', 'Female', 0),
                        (126, 'Prabhat', 'en-IN-PrabhatNeural', 'Male', 0),
                        (127, 'Rehaan', 'en-IN-RehaanNeural', 'Male', 0),
                        (128, 'Asilia', 'en-KE-AsiliaNeural', 'Female', 0),
                        (129, 'Chilemba', 'en-KE-ChilembaNeural', 'Male', 0),
                        (130, 'Ezinne', 'en-NG-EzinneNeural', 'Female', 0),
                        (131, 'Abeo', 'en-NG-AbeoNeural', 'Male', 0),
                        (132, 'Molly', 'en-NZ-MollyNeural', 'Female', 0),
                        (133, 'Mitchell', 'en-NZ-MitchellNeural', 'Male', 0),
                        (134, 'Rosa', 'en-PH-RosaNeural', 'Female', 0),
                        (135, 'James', 'en-PH-JamesNeural', 'Male', 0),
                        (136, 'Luna', 'en-SG-LunaNeural', 'Female', 0),
                        (137, 'Wayne', 'en-SG-WayneNeural', 'Male', 0),
                        (138, 'Imani', 'en-TZ-ImaniNeural', 'Female', 0),
                        (139, 'Elimu', 'en-TZ-ElimuNeural', 'Male', 0),
                        (140, 'Ava Multilingual', 'en-US-AvaMultilingualNeural', 'Female', 0),
                        (141, 'Andrew Multilingual', 'en-US-AndrewMultilingualNeural', 'Male', 0),
                        (142, 'Emma Multilingual', 'en-US-EmmaMultilingualNeural', 'Female', 0),
                        (143, 'Brian Multilingual', 'en-US-BrianMultilingualNeural', 'Male', 0),
                        (144, 'Ava', 'en-US-AvaNeural', 'Female', 0),
                        (145, 'Andrew', 'en-US-AndrewNeural', 'Male', 0),
                        (146, 'Emma', 'en-US-EmmaNeural', 'Female', 0),
                        (147, 'Brian', 'en-US-BrianNeural', 'Male', 0),
                        (148, 'Jenny', 'en-US-JennyNeural', 'Female', 0),
                        (149, 'Guy', 'en-US-GuyNeural', 'Male', 0),
                        (150, 'Aria', 'en-US-AriaNeural', 'Female', 0),
                        (151, 'Davis', 'en-US-DavisNeural', 'Male', 0),
                        (152, 'Jane', 'en-US-JaneNeural', 'Female', 0),
                        (153, 'Jason', 'en-US-JasonNeural', 'Male', 0),
                        (154, 'Kai', 'en-US-KaiNeural', 'Male', 0),
                        (155, 'Luna', 'en-US-LunaNeural', 'Female', 0),
                        (156, 'Sara', 'en-US-SaraNeural', 'Female', 0),
                        (157, 'Tony', 'en-US-TonyNeural', 'Male', 0),
                        (158, 'Nancy', 'en-US-NancyNeural', 'Female', 0),
                        (159, 'Cora Multilingual', 'en-US-CoraMultilingualNeural', 'Female', 0),
                        (160, 'Christopher Multilingual', 'en-US-ChristopherMultilingualNeural', 'Male', 0),
                        (161, 'Brandon Multilingual', 'en-US-BrandonMultilingualNeural', 'Male', 0),
                        (162, 'Amber', 'en-US-AmberNeural', 'Female', 0),
                        (163, 'Ana', 'en-US-AnaNeural', 'Female', 0),
                        (164, 'Ashley', 'en-US-AshleyNeural', 'Female', 0),
                        (165, 'Brandon', 'en-US-BrandonNeural', 'Male', 0),
                        (166, 'Christopher', 'en-US-ChristopherNeural', 'Male', 0),
                        (167, 'Cora', 'en-US-CoraNeural', 'Female', 0),
                        (168, 'Elizabeth', 'en-US-ElizabethNeural', 'Female', 0),
                        (169, 'Eric', 'en-US-EricNeural', 'Male', 0),
                        (170, 'Jacob', 'en-US-JacobNeural', 'Male', 0),
                        (171, 'Jenny Multilingual', 'en-US-JennyMultilingualNeural', 'Female', 0),
                        (172, 'Michelle', 'en-US-MichelleNeural', 'Female', 0),
                        (173, 'Monica', 'en-US-MonicaNeural', 'Female', 0),
                        (174, 'Roger', 'en-US-RogerNeural', 'Male', 0),
                        (175, 'Ryan Multilingual', 'en-US-RyanMultilingualNeural', 'Male', 0),
                        (176, 'Steffan', 'en-US-SteffanNeural', 'Male', 0),
                        (177, 'Adam Multilingual', 'en-US-AdamMultilingualNeural', 'Male', 0),
                        (178, 'AIGenerate1', 'en-US-AIGenerate1Neural', 'Male', 0),
                        (179, 'AIGenerate2', 'en-US-AIGenerate2Neural', 'Female', 0),
                        (180, 'Alloy Turbo Multilingual', 'en-US-AlloyTurboMultilingualNeural', 'Male', 0),
                        (181, 'Amanda Multilingual', 'en-US-AmandaMultilingualNeural', 'Female', 0),
                        (182, 'Blue', 'en-US-BlueNeural', 'Neutral', 0),
                        (183, 'Davis Multilingual', 'en-US-DavisMultilingualNeural', 'Male', 0),
                        (184, 'Derek Multilingual', 'en-US-DerekMultilingualNeural', 'Male', 0),
                        (185, 'Dustin Multilingual', 'en-US-DustinMultilingualNeural', 'Male', 0),
                        (186, 'Echo Turbo Multilingual', 'en-US-EchoTurboMultilingualNeural', 'Male', 0),
                        (187, 'Evelyn Multilingual', 'en-US-EvelynMultilingualNeural', 'Female', 0),
                        (188, 'Fable Turbo Multilingual', 'en-US-FableTurboMultilingualNeural', 'Neutral', 0),
                        (189, 'Lewis Multilingual', 'en-US-LewisMultilingualNeural', 'Male', 0),
                        (190, 'Lola Multilingual', 'en-US-LolaMultilingualNeural', 'Female', 0),
                        (191, 'Nancy Multilingual', 'en-US-NancyMultilingualNeural', 'Female', 0),
                        (192, 'Nova Turbo Multilingual', 'en-US-NovaTurboMultilingualNeural', 'Female', 0),
                        (193, 'Onyx Turbo Multilingual', 'en-US-OnyxTurboMultilingualNeural', 'Male', 0),
                        (194, 'Phoebe Multilingual', 'en-US-PhoebeMultilingualNeural', 'Female', 0),
                        (195, 'Samuel Multilingual', 'en-US-SamuelMultilingualNeural', 'Male', 0),
                        (196, 'Serena Multilingual', 'en-US-SerenaMultilingualNeural', 'Female', 0),
                        (197, 'Shimmer Turbo Multilingual', 'en-US-ShimmerTurboMultilingualNeural', 'Female', 0),
                        (198, 'Steffan Multilingual', 'en-US-SteffanMultilingualNeural', 'Male', 0),
                        (199, 'Andrew Dragon HD Latest', 'en-US-Andrew:DragonHDLatestNeural', 'Male', 0),
                        (200, 'Andrew2 Dragon HD Latest', 'en-US-Andrew2:DragonHDLatestNeural', 'Male', 0),
                        (201, 'Aria Dragon HD Latest', 'en-US-Aria:DragonHDLatestNeural', 'Female', 0),
                        (202, 'Ava Dragon HD Latest', 'en-US-Ava:DragonHDLatestNeural', 'Female', 0),
                        (203, 'Brian Dragon HD Latest', 'en-US-Brian:DragonHDLatestNeural', 'Male', 0),
                        (204, 'Davis Dragon HD Latest', 'en-US-Davis:DragonHDLatestNeural', 'Male', 0),
                        (205, 'Emma Dragon HD Latest', 'en-US-Emma:DragonHDLatestNeural', 'Female', 0),
                        (206, 'Emma2 Dragon HD Latest', 'en-US-Emma2:DragonHDLatestNeural', 'Female', 0),
                        (207, 'Jenny Dragon HD Latest', 'en-US-Jenny:DragonHDLatestNeural', 'Female', 0),
                        (208, 'Steffan Dragon HD Latest', 'en-US-Steffan:DragonHDLatestNeural', 'Male', 0),
                        (209, 'Leah', 'en-ZA-LeahNeural', 'Female', 0),
                        (210, 'Luke', 'en-ZA-LukeNeural', 'Male', 0),
                        (211, 'Elena', 'es-AR-ElenaNeural', 'Female', 0),
                        (212, 'Tomas', 'es-AR-TomasNeural', 'Male', 0),
                        (213, 'Sofia', 'es-BO-SofiaNeural', 'Female', 0),
                        (214, 'Marcelo', 'es-BO-MarceloNeural', 'Male', 0),
                        (215, 'Catalina', 'es-CL-CatalinaNeural', 'Female', 0),
                        (216, 'Lorenzo', 'es-CL-LorenzoNeural', 'Male', 0),
                        (217, 'Salome', 'es-CO-SalomeNeural', 'Female', 0),
                        (218, 'Gonzalo', 'es-CO-GonzaloNeural', 'Male', 0),
                        (219, 'Maria', 'es-CR-MariaNeural', 'Female', 0),
                        (220, 'Juan', 'es-CR-JuanNeural', 'Male', 0),
                        (221, 'Belkys', 'es-CU-BelkysNeural', 'Female', 0),
                        (222, 'Manuel', 'es-CU-ManuelNeural', 'Male', 0),
                        (223, 'Ramona', 'es-DO-RamonaNeural', 'Female', 0),
                        (224, 'Emilio', 'es-DO-EmilioNeural', 'Male', 0),
                        (225, 'Andrea', 'es-EC-AndreaNeural', 'Female', 0),
                        (226, 'Luis', 'es-EC-LuisNeural', 'Male', 0),
                        (227, 'Elvira', 'es-ES-ElviraNeural', 'Female', 0),
                        (228, 'Alvaro', 'es-ES-AlvaroNeural', 'Male', 0),
                        (229, 'Arabella Multilingual', 'es-ES-ArabellaMultilingualNeural', 'Female', 0),
                        (230, 'Isidora Multilingual', 'es-ES-IsidoraMultilingualNeural', 'Female', 0),
                        (231, 'Tristan Multilingual', 'es-ES-TristanMultilingualNeural', 'Male', 0),
                        (232, 'Ximena Multilingual', 'es-ES-XimenaMultilingualNeural', 'Female', 0),
                        (233, 'Abril', 'es-ES-AbrilNeural', 'Female', 0),
                        (234, 'Arnau', 'es-ES-ArnauNeural', 'Male', 0),
                        (235, 'Dario', 'es-ES-DarioNeural', 'Male', 0),
                        (236, 'Elias', 'es-ES-EliasNeural', 'Male', 0),
                        (237, 'Estrella', 'es-ES-EstrellaNeural', 'Female', 0),
                        (238, 'Irene', 'es-ES-IreneNeural', 'Female', 0),
                        (239, 'Laia', 'es-ES-LaiaNeural', 'Female', 0),
                        (240, 'Lia', 'es-ES-LiaNeural', 'Female', 0),
                        (241, 'Nil', 'es-ES-NilNeural', 'Male', 0),
                        (242, 'Saul', 'es-ES-SaulNeural', 'Male', 0),
                        (243, 'Teo', 'es-ES-TeoNeural', 'Male', 0),
                        (244, 'Triana', 'es-ES-TrianaNeural', 'Female', 0),
                        (245, 'Vera', 'es-ES-VeraNeural', 'Female', 0),
                        (246, 'Ximena', 'es-ES-XimenaNeural', 'Female', 0),
                        (247, 'Teresa', 'es-GQ-TeresaNeural', 'Female', 0),
                        (248, 'Javier', 'es-GQ-JavierNeural', 'Male', 0),
                        (249, 'Marta', 'es-GT-MartaNeural', 'Female', 0),
                        (250, 'Andres', 'es-GT-AndresNeural', 'Male', 0),
                        (251, 'Karla', 'es-HN-KarlaNeural', 'Female', 0),
                        (252, 'Carlos', 'es-HN-CarlosNeural', 'Male', 0),
                        (253, 'Dalia', 'es-MX-DaliaNeural', 'Female', 0),
                        (254, 'Jorge', 'es-MX-JorgeNeural', 'Male', 0),
                        (255, 'Beatriz', 'es-MX-BeatrizNeural', 'Female', 0),
                        (256, 'Candela', 'es-MX-CandelaNeural', 'Female', 0),
                        (257, 'Carlota', 'es-MX-CarlotaNeural', 'Female', 0),
                        (258, 'Cecilio', 'es-MX-CecilioNeural', 'Male', 0),
                        (259, 'Gerardo', 'es-MX-GerardoNeural', 'Male', 0),
                        (260, 'Larissa', 'es-MX-LarissaNeural', 'Female', 0),
                        (261, 'Liberto', 'es-MX-LibertoNeural', 'Male', 0),
                        (262, 'Luciano', 'es-MX-LucianoNeural', 'Male', 0),
                        (263, 'Marina', 'es-MX-MarinaNeural', 'Female', 0),
                        (264, 'Nuria', 'es-MX-NuriaNeural', 'Female', 0),
                        (265, 'Pelayo', 'es-MX-PelayoNeural', 'Male', 0),
                        (266, 'Renata', 'es-MX-RenataNeural', 'Female', 0),
                        (267, 'Yago', 'es-MX-YagoNeural', 'Male', 0),
                        (268, 'Yolanda', 'es-NI-YolandaNeural', 'Female', 0),
                        (269, 'Federico', 'es-NI-FedericoNeural', 'Male', 0),
                        (270, 'Margarita', 'es-PA-MargaritaNeural', 'Female', 0),
                        (271, 'Roberto', 'es-PA-RobertoNeural', 'Male', 0),
                        (272, 'Camila', 'es-PE-CamilaNeural', 'Female', 0),
                        (273, 'Alex', 'es-PE-AlexNeural', 'Male', 0),
                        (274, 'Karina', 'es-PR-KarinaNeural', 'Female', 0),
                        (275, 'Victor', 'es-PR-VictorNeural', 'Male', 0),
                        (276, 'Tania', 'es-PY-TaniaNeural', 'Female', 0),
                        (277, 'Mario', 'es-PY-MarioNeural', 'Male', 0),
                        (278, 'Lorena', 'es-SV-LorenaNeural', 'Female', 0),
                        (279, 'Rodrigo', 'es-SV-RodrigoNeural', 'Male', 0),
                        (280, 'Paloma', 'es-US-PalomaNeural', 'Female', 0),
                        (281, 'Alonso', 'es-US-AlonsoNeural', 'Male', 0),
                        (282, 'Valentina', 'es-UY-ValentinaNeural', 'Female', 0),
                        (283, 'Mateo', 'es-UY-MateoNeural', 'Male', 0),
                        (284, 'Paola', 'es-VE-PaolaNeural', 'Female', 0),
                        (285, 'Sebastian', 'es-VE-SebastianNeural', 'Male', 0),
                        (286, 'Anu', 'et-EE-AnuNeural', 'Female', 0),
                        (287, 'Kert', 'et-EE-KertNeural', 'Male', 0),
                        (288, 'Ainhoa', 'eu-ES-AinhoaNeural', 'Female', 0),
                        (289, 'Ander', 'eu-ES-AnderNeural', 'Male', 0),
                        (290, 'Dilara', 'fa-IR-DilaraNeural', 'Female', 0),
                        (291, 'Farid', 'fa-IR-FaridNeural', 'Male', 0),
                        (292, 'Selma', 'fi-FI-SelmaNeural', 'Female', 0),
                        (293, 'Harri', 'fi-FI-HarriNeural', 'Male', 0),
                        (294, 'Noora', 'fi-FI-NooraNeural', 'Female', 0),
                        (295, 'Blessica', 'fil-PH-BlessicaNeural', 'Female', 0),
                        (296, 'Angelo', 'fil-PH-AngeloNeural', 'Male', 0),
                        (297, 'Charline', 'fr-BE-CharlineNeural', 'Female', 0),
                        (298, 'Gerard', 'fr-BE-GerardNeural', 'Male', 0),
                        (299, 'Sylvie', 'fr-CA-SylvieNeural', 'Female', 0),
                        (300, 'Jean', 'fr-CA-JeanNeural', 'Male', 0),
                        (301, 'Antoine', 'fr-CA-AntoineNeural', 'Male', 0),
                        (302, 'Thierry', 'fr-CA-ThierryNeural', 'Male', 0),
                        (303, 'Ariane', 'fr-CH-ArianeNeural', 'Female', 0),
                        (304, 'Fabrice', 'fr-CH-FabriceNeural', 'Male', 0),
                        (305, 'Denise', 'fr-FR-DeniseNeural', 'Female', 0),
                        (306, 'Henri', 'fr-FR-HenriNeural', 'Male', 0),
                        (307, 'Vivienne Multilingual', 'fr-FR-VivienneMultilingualNeural', 'Female', 0),
                        (308, 'Remy Multilingual', 'fr-FR-RemyMultilingualNeural', 'Male', 0),
                        (309, 'Lucien Multilingual', 'fr-FR-LucienMultilingualNeural', 'Male', 0),
                        (310, 'Alain', 'fr-FR-AlainNeural', 'Male', 0),
                        (311, 'Brigitte', 'fr-FR-BrigitteNeural', 'Female', 0),
                        (312, 'Celeste', 'fr-FR-CelesteNeural', 'Female', 0),
                        (313, 'Claude', 'fr-FR-ClaudeNeural', 'Male', 0),
                        (314, 'Coralie', 'fr-FR-CoralieNeural', 'Female', 0),
                        (315, 'Eloise', 'fr-FR-EloiseNeural', 'Female', 0),
                        (316, 'Jacqueline', 'fr-FR-JacquelineNeural', 'Female', 0),
                        (317, 'Jerome', 'fr-FR-JeromeNeural', 'Male', 0),
                        (318, 'Josephine', 'fr-FR-JosephineNeural', 'Female', 0),
                        (319, 'Maurice', 'fr-FR-MauriceNeural', 'Male', 0),
                        (320, 'Yves', 'fr-FR-YvesNeural', 'Male', 0),
                        (321, 'Yvette', 'fr-FR-YvetteNeural', 'Female', 0),
                        (322, 'Orla', 'ga-IE-OrlaNeural', 'Female', 0),
                        (323, 'Colm', 'ga-IE-ColmNeural', 'Male', 0),
                        (324, 'Sabela', 'gl-ES-SabelaNeural', 'Female', 0),
                        (325, 'Roi', 'gl-ES-RoiNeural', 'Male', 0),
                        (326, 'Dhwani', 'gu-IN-DhwaniNeural', 'Female', 0),
                        (327, 'Niranjan', 'gu-IN-NiranjanNeural', 'Male', 0),
                        (328, 'Hila', 'he-IL-HilaNeural', 'Female', 0),
                        (329, 'Avri', 'he-IL-AvriNeural', 'Male', 0),
                        (330, 'Aarav', 'hi-IN-AaravNeural', 'Male', 0),
                        (331, 'Ananya', 'hi-IN-AnanyaNeural', 'Female', 0),
                        (332, 'Kavya', 'hi-IN-KavyaNeural', 'Female', 0),
                        (333, 'Kunal', 'hi-IN-KunalNeural', 'Male', 0),
                        (334, 'Rehaan', 'hi-IN-RehaanNeural', 'Male', 0),
                        (335, 'Swara', 'hi-IN-SwaraNeural', 'Female', 0),
                        (336, 'Madhur', 'hi-IN-MadhurNeural', 'Male', 0),
                        (337, 'Gabrijela', 'hr-HR-GabrijelaNeural', 'Female', 0),
                        (338, 'Srecko', 'hr-HR-SreckoNeural', 'Male', 0),
                        (339, 'Noemi', 'hu-HU-NoemiNeural', 'Female', 0),
                        (340, 'Tamas', 'hu-HU-TamasNeural', 'Male', 0),
                        (341, 'Anahit', 'hy-AM-AnahitNeural', 'Female', 0),
                        (342, 'Hayk', 'hy-AM-HaykNeural', 'Male', 0),
                        (343, 'Gadis', 'id-ID-GadisNeural', 'Female', 0),
                        (344, 'Ardi', 'id-ID-ArdiNeural', 'Male', 0),
                        (345, 'Gudrun', 'is-IS-GudrunNeural', 'Female', 0),
                        (346, 'Gunnar', 'is-IS-GunnarNeural', 'Male', 0),
                        (347, 'Elsa', 'it-IT-ElsaNeural', 'Female', 0),
                        (348, 'Isabella', 'it-IT-IsabellaNeural', 'Female', 0),
                        (349, 'Diego', 'it-IT-DiegoNeural', 'Male', 0),
                        (350, 'Alessio Multilingual', 'it-IT-AlessioMultilingualNeural', 'Male', 0),
                        (351, 'Isabella Multilingual', 'it-IT-IsabellaMultilingualNeural', 'Female', 0),
                        (352, 'Giuseppe Multilingual', 'it-IT-GiuseppeMultilingualNeural', 'Male', 0),
                        (353, 'Marcello Multilingual', 'it-IT-MarcelloMultilingualNeural', 'Male', 0),
                        (354, 'Benigno', 'it-IT-BenignoNeural', 'Male', 0),
                        (355, 'Calimero', 'it-IT-CalimeroNeural', 'Male', 0),
                        (356, 'Cataldo', 'it-IT-CataldoNeural', 'Male', 0),
                        (357, 'Fabiola', 'it-IT-FabiolaNeural', 'Female', 0),
                        (358, 'Fiamma', 'it-IT-FiammaNeural', 'Female', 0),
                        (359, 'Gianni', 'it-IT-GianniNeural', 'Male', 0),
                        (360, 'Giuseppe', 'it-IT-GiuseppeNeural', 'Male', 0),
                        (361, 'Imelda', 'it-IT-ImeldaNeural', 'Female', 0),
                        (362, 'Irma', 'it-IT-IrmaNeural', 'Female', 0),
                        (363, 'Lisandro', 'it-IT-LisandroNeural', 'Male', 0),
                        (364, 'Palmira', 'it-IT-PalmiraNeural', 'Female', 0),
                        (365, 'Pierina', 'it-IT-PierinaNeural', 'Female', 0),
                        (366, 'Rinaldo', 'it-IT-RinaldoNeural', 'Male', 0),
                        (367, 'Siqiniq', 'iu-Cans-CA-SiqiniqNeural', 'Female', 0),
                        (368, 'Taqqiq', 'iu-Cans-CA-TaqqiqNeural', 'Male', 0),
                        (369, 'Siqiniq', 'iu-Latn-CA-SiqiniqNeural', 'Female', 0),
                        (370, 'Taqqiq', 'iu-Latn-CA-TaqqiqNeural', 'Male', 0),
                        (371, 'Nanami', 'ja-JP-NanamiNeural', 'Female', 0),
                        (372, 'Keita', 'ja-JP-KeitaNeural', 'Male', 0),
                        (373, 'Aoi', 'ja-JP-AoiNeural', 'Female', 0),
                        (374, 'Daichi', 'ja-JP-DaichiNeural', 'Male', 0),
                        (375, 'Mayu', 'ja-JP-MayuNeural', 'Female', 0),
                        (376, 'Naoki', 'ja-JP-NaokiNeural', 'Male', 0),
                        (377, 'Shiori', 'ja-JP-ShioriNeural', 'Female', 0),
                        (378, 'Masaru Multilingual', 'ja-JP-MasaruMultilingualNeural', 'Male', 0),
                        (379, 'Masaru Dragon HD Latest', 'ja-JP-Masaru:DragonHDLatestNeural', 'Male', 0),
                        (380, 'Siti', 'jv-ID-SitiNeural', 'Female', 0),
                        (381, 'Dimas', 'jv-ID-DimasNeural', 'Male', 0),
                        (382, 'Eka', 'ka-GE-EkaNeural', 'Female', 0),
                        (383, 'Giorgi', 'ka-GE-GiorgiNeural', 'Male', 0),
                        (384, 'Aigul', 'kk-KZ-AigulNeural', 'Female', 0),
                        (385, 'Daulet', 'kk-KZ-DauletNeural', 'Male', 0),
                        (386, 'Sreymom', 'km-KH-SreymomNeural', 'Female', 0),
                        (387, 'Piseth', 'km-KH-PisethNeural', 'Male', 0),
                        (388, 'Sapna', 'kn-IN-SapnaNeural', 'Female', 0),
                        (389, 'Gagan', 'kn-IN-GaganNeural', 'Male', 0),
                        (390, 'Sun-Hi', 'ko-KR-SunHiNeural', 'Female', 0),
                        (391, 'InJoon', 'ko-KR-InJoonNeural', 'Male', 0),
                        (392, 'Hyunsu Multilingual', 'ko-KR-HyunsuMultilingualNeural', 'Male', 0),
                        (393, 'BongJin', 'ko-KR-BongJinNeural', 'Male', 0),
                        (394, 'GookMin', 'ko-KR-GookMinNeural', 'Male', 0),
                        (395, 'Hyunsu', 'ko-KR-HyunsuNeural', 'Male', 0),
                        (396, 'JiMin', 'ko-KR-JiMinNeural', 'Female', 0),
                        (397, 'SeoHyeon', 'ko-KR-SeoHyeonNeural', 'Female', 0),
                        (398, 'SoonBok', 'ko-KR-SoonBokNeural', 'Female', 0),
                        (399, 'YuJin', 'ko-KR-YuJinNeural', 'Female', 0),
                        (400, 'Keomany', 'lo-LA-KeomanyNeural', 'Female', 0),
                        (401, 'Chanthavong', 'lo-LA-ChanthavongNeural', 'Male', 0),
                        (402, 'Ona', 'lt-LT-OnaNeural', 'Female', 0),
                        (403, 'Leonas', 'lt-LT-LeonasNeural', 'Male', 0),
                        (404, 'Everita', 'lv-LV-EveritaNeural', 'Female', 0),
                        (405, 'Nils', 'lv-LV-NilsNeural', 'Male', 0),
                        (406, 'Marija', 'mk-MK-MarijaNeural', 'Female', 0),
                        (407, 'Aleksandar', 'mk-MK-AleksandarNeural', 'Male', 0),
                        (408, 'Sobhana', 'ml-IN-SobhanaNeural', 'Female', 0),
                        (409, 'Midhun', 'ml-IN-MidhunNeural', 'Male', 0),
                        (410, 'Yesui', 'mn-MN-YesuiNeural', 'Female', 0),
                        (411, 'Bataa', 'mn-MN-BataaNeural', 'Male', 0),
                        (412, 'Aarohi', 'mr-IN-AarohiNeural', 'Female', 0),
                        (413, 'Manohar', 'mr-IN-ManoharNeural', 'Male', 0),
                        (414, 'Yasmin', 'ms-MY-YasminNeural', 'Female', 0),
                        (415, 'Osman', 'ms-MY-OsmanNeural', 'Male', 0),
                        (416, 'Grace', 'mt-MT-GraceNeural', 'Female', 0),
                        (417, 'Joseph', 'mt-MT-JosephNeural', 'Male', 0),
                        (418, 'Nilar', 'my-MM-NilarNeural', 'Female', 0),
                        (419, 'Thiha', 'my-MM-ThihaNeural', 'Male', 0),
                        (420, 'Pernille', 'nb-NO-PernilleNeural', 'Female', 0),
                        (421, 'Finn', 'nb-NO-FinnNeural', 'Male', 0),
                        (422, 'Iselin', 'nb-NO-IselinNeural', 'Female', 0),
                        (423, 'Hemkala', 'ne-NP-HemkalaNeural', 'Female', 0),
                        (424, 'Sagar', 'ne-NP-SagarNeural', 'Male', 0),
                        (425, 'Dena', 'nl-BE-DenaNeural', 'Female', 0),
                        (426, 'Arnaud', 'nl-BE-ArnaudNeural', 'Male', 0),
                        (427, 'Fenna', 'nl-NL-FennaNeural', 'Female', 0),
                        (428, 'Maarten', 'nl-NL-MaartenNeural', 'Male', 0),
                        (429, 'Colette', 'nl-NL-ColetteNeural', 'Female', 0),
                        (430, 'Subhasini', 'or-IN-SubhasiniNeural', 'Female', 0),
                        (431, 'Sukant', 'or-IN-SukantNeural', 'Male', 0),
                        (432, 'Ojas', 'pa-IN-OjasNeural', 'Male', 0),
                        (433, 'Vaani', 'pa-IN-VaaniNeural', 'Female', 0),
                        (434, 'Agnieszka', 'pl-PL-AgnieszkaNeural', 'Female', 0),
                        (435, 'Marek', 'pl-PL-MarekNeural', 'Male', 0),
                        (436, 'Zofia', 'pl-PL-ZofiaNeural', 'Female', 0),
                        (437, 'Latifa', 'ps-AF-LatifaNeural', 'Female', 0),
                        (438, 'Gul Nawaz', 'ps-AF-GulNawazNeural', 'Male', 0),
                        (439, 'Francisca', 'pt-BR-FranciscaNeural', 'Female', 0),
                        (440, 'Antonio', 'pt-BR-AntonioNeural', 'Male', 0),
                        (441, 'Macerio Multilingual', 'pt-BR-MacerioMultilingualNeural', 'Male', 0),
                        (442, 'Thalita Multilingual', 'pt-BR-ThalitaMultilingualNeural', 'Female', 0),
                        (443, 'Brenda', 'pt-BR-BrendaNeural', 'Female', 0),
                        (444, 'Donato', 'pt-BR-DonatoNeural', 'Male', 0),
                        (445, 'Elza', 'pt-BR-ElzaNeural', 'Female', 0),
                        (446, 'Fabio', 'pt-BR-FabioNeural', 'Male', 0),
                        (447, 'Giovanna', 'pt-BR-GiovannaNeural', 'Female', 0),
                        (448, 'Humberto', 'pt-BR-HumbertoNeural', 'Male', 0),
                        (449, 'Julio', 'pt-BR-JulioNeural', 'Male', 0),
                        (450, 'Leila', 'pt-BR-LeilaNeural', 'Female', 0),
                        (451, 'Leticia', 'pt-BR-LeticiaNeural', 'Female', 0),
                        (452, 'Manuela', 'pt-BR-ManuelaNeural', 'Female', 0),
                        (453, 'Nicolau', 'pt-BR-NicolauNeural', 'Male', 0),
                        (454, 'Thalita', 'pt-BR-ThalitaNeural', 'Female', 0),
                        (455, 'Valerio', 'pt-BR-ValerioNeural', 'Male', 0),
                        (456, 'Yara', 'pt-BR-YaraNeural', 'Female', 0),
                        (457, 'Raquel', 'pt-PT-RaquelNeural', 'Female', 0),
                        (458, 'Duarte', 'pt-PT-DuarteNeural', 'Male', 0),
                        (459, 'Fernanda', 'pt-PT-FernandaNeural', 'Female', 0),
                        (460, 'Alina', 'ro-RO-AlinaNeural', 'Female', 0),
                        (461, 'Emil', 'ro-RO-EmilNeural', 'Male', 0),
                        (462, 'Svetlana', 'ru-RU-SvetlanaNeural', 'Female', 0),
                        (463, 'Dmitry', 'ru-RU-DmitryNeural', 'Male', 0),
                        (464, 'Dariya', 'ru-RU-DariyaNeural', 'Female', 0),
                        (465, 'Thilini', 'si-LK-ThiliniNeural', 'Female', 0),
                        (466, 'Sameera', 'si-LK-SameeraNeural', 'Male', 0),
                        (467, 'Viktoria', 'sk-SK-ViktoriaNeural', 'Female', 0),
                        (468, 'Lukas', 'sk-SK-LukasNeural', 'Male', 0),
                        (469, 'Petra', 'sl-SI-PetraNeural', 'Female', 0),
                        (470, 'Rok', 'sl-SI-RokNeural', 'Male', 0),
                        (471, 'Ubax', 'so-SO-UbaxNeural', 'Female', 0),
                        (472, 'Muuse', 'so-SO-MuuseNeural', 'Male', 0),
                        (473, 'Anila', 'sq-AL-AnilaNeural', 'Female', 0),
                        (474, 'Ilir', 'sq-AL-IlirNeural', 'Male', 0),
                        (475, 'Nicholas', 'sr-Latn-RS-NicholasNeural', 'Male', 0),
                        (476, 'Sophie', 'sr-Latn-RS-SophieNeural', 'Female', 0),
                        (477, 'Sophie', 'sr-RS-SophieNeural', 'Female', 0),
                        (478, 'Nicholas', 'sr-RS-NicholasNeural', 'Male', 0),
                        (479, 'Tuti', 'su-ID-TutiNeural', 'Female', 0),
                        (480, 'Jajang', 'su-ID-JajangNeural', 'Male', 0),
                        (481, 'Sofie', 'sv-SE-SofieNeural', 'Female', 0),
                        (482, 'Mattias', 'sv-SE-MattiasNeural', 'Male', 0),
                        (483, 'Hillevi', 'sv-SE-HilleviNeural', 'Female', 0),
                        (484, 'Zuri', 'sw-KE-ZuriNeural', 'Female', 0),
                        (485, 'Rafiki', 'sw-KE-RafikiNeural', 'Male', 0),
                        (486, 'Rehema', 'sw-TZ-RehemaNeural', 'Female', 0),
                        (487, 'Daudi', 'sw-TZ-DaudiNeural', 'Male', 0),
                        (488, 'Pallavi', 'ta-IN-PallaviNeural', 'Female', 0),
                        (489, 'Valluvar', 'ta-IN-ValluvarNeural', 'Male', 0),
                        (490, 'Saranya', 'ta-LK-SaranyaNeural', 'Female', 0),
                        (491, 'Kumar', 'ta-LK-KumarNeural', 'Male', 0),
                        (492, 'Kani', 'ta-MY-KaniNeural', 'Female', 0),
                        (493, 'Surya', 'ta-MY-SuryaNeural', 'Male', 0),
                        (494, 'Venba', 'ta-SG-VenbaNeural', 'Female', 0),
                        (495, 'Anbu', 'ta-SG-AnbuNeural', 'Male', 0),
                        (496, 'Shruti', 'te-IN-ShrutiNeural', 'Female', 0),
                        (497, 'Mohan', 'te-IN-MohanNeural', 'Male', 0),
                        (498, 'Premwadee', 'th-TH-PremwadeeNeural', 'Female', 0),
                        (499, 'Niwat', 'th-TH-NiwatNeural', 'Male', 0),
                        (500, 'Achara', 'th-TH-AcharaNeural', 'Female', 0),
                        (501, 'Emel', 'tr-TR-EmelNeural', 'Female', 0),
                        (502, 'Ahmet', 'tr-TR-AhmetNeural', 'Male', 0),
                        (503, 'Polina', 'uk-UA-PolinaNeural', 'Female', 0),
                        (504, 'Ostap', 'uk-UA-OstapNeural', 'Male', 0),
                        (505, 'Gul', 'ur-IN-GulNeural', 'Female', 0),
                        (506, 'Salman', 'ur-IN-SalmanNeural', 'Male', 0),
                        (507, 'Uzma', 'ur-PK-UzmaNeural', 'Female', 0),
                        (508, 'Asad', 'ur-PK-AsadNeural', 'Male', 0),
                        (509, 'Madina', 'uz-UZ-MadinaNeural', 'Female', 0),
                        (510, 'Sardor', 'uz-UZ-SardorNeural', 'Male', 0),
                        (511, 'HoaiMy', 'vi-VN-HoaiMyNeural', 'Female', 0),
                        (512, 'NamMinh', 'vi-VN-NamMinhNeural', 'Male', 0),
                        (513, 'Xiaotong', 'wuu-CN-XiaotongNeural', 'Female', 0),
                        (514, 'Yunzhe', 'wuu-CN-YunzheNeural', 'Male', 0),
                        (515, 'XiaoMin', 'yue-CN-XiaoMinNeural', 'Female', 0),
                        (516, 'YunSong', 'yue-CN-YunSongNeural', 'Male', 0),
                        (517, 'Xiaoxiao', 'zh-CN-XiaoxiaoNeural', 'Female', 0),
                        (518, 'Yunxi', 'zh-CN-YunxiNeural', 'Male', 0),
                        (519, 'Yunjian', 'zh-CN-YunjianNeural', 'Male', 0),
                        (520, 'Xiaoyi', 'zh-CN-XiaoyiNeural', 'Female', 0),
                        (521, 'Yunyang', 'zh-CN-YunyangNeural', 'Male', 0),
                        (522, 'Xiaochen', 'zh-CN-XiaochenNeural', 'Female', 0),
                        (523, 'Xiaochen Multilingual', 'zh-CN-XiaochenMultilingualNeural', 'Female', 0),
                        (524, 'Xiaohan', 'zh-CN-XiaohanNeural', 'Female', 0),
                        (525, 'Xiaomeng', 'zh-CN-XiaomengNeural', 'Female', 0),
                        (526, 'Xiaomo', 'zh-CN-XiaomoNeural', 'Female', 0),
                        (527, 'Xiaoqiu', 'zh-CN-XiaoqiuNeural', 'Female', 0),
                        (528, 'Xiaorou', 'zh-CN-XiaorouNeural', 'Female', 0),
                        (529, 'Xiaorui', 'zh-CN-XiaoruiNeural', 'Female', 0),
                        (530, 'Xiaoshuang', 'zh-CN-XiaoshuangNeural', 'Female', 0),
                        (531, 'Xiaoxiao Dialects', 'zh-CN-XiaoxiaoDialectsNeural', 'Female', 0),
                        (532, 'Xiaoxiao Multilingual', 'zh-CN-XiaoxiaoMultilingualNeural', 'Female', 0),
                        (533, 'Xiaoyan', 'zh-CN-XiaoyanNeural', 'Female', 0),
                        (534, 'Xiaoyou', 'zh-CN-XiaoyouNeural', 'Female', 0),
                        (535, 'Xiaoyu Multilingual', 'zh-CN-XiaoyuMultilingualNeural', 'Female', 0),
                        (536, 'Xiaozhen', 'zh-CN-XiaozhenNeural', 'Female', 0),
                        (537, 'Yunfeng', 'zh-CN-YunfengNeural', 'Male', 0),
                        (538, 'Yunhao', 'zh-CN-YunhaoNeural', 'Male', 0),
                        (539, 'Yunjie', 'zh-CN-YunjieNeural', 'Male', 0),
                        (540, 'Yunxia', 'zh-CN-YunxiaNeural', 'Male', 0),
                        (541, 'Yunye', 'zh-CN-YunyeNeural', 'Male', 0),
                        (542, 'Yunyi Multilingual', 'zh-CN-YunyiMultilingualNeural', 'Male', 0),
                        (543, 'Yunze', 'zh-CN-YunzeNeural', 'Male', 0),
                        (544, 'Yunfan Multilingual', 'zh-CN-YunfanMultilingualNeural', 'Male', 0),
                        (545, 'Yunxiao Multilingual', 'zh-CN-YunxiaoMultilingualNeural', 'Male', 0),
                        (546, 'Xiaochen Dragon HD Latest', 'zh-CN-Xiaochen:DragonHDLatestNeural', 'Female', 0),
                        (547, 'Yunqi', 'zh-CN-guangxi-YunqiNeural', 'Male', 0),
                        (548, 'Yundeng', 'zh-CN-henan-YundengNeural', 'Male', 0),
                        (549, 'Xiaobei', 'zh-CN-liaoning-XiaobeiNeural', 'Female', 0),
                        (550, 'Yunbiao', 'zh-CN-liaoning-YunbiaoNeural', 'Male', 0),
                        (551, 'Xiaoni', 'zh-CN-shaanxi-XiaoniNeural', 'Female', 0),
                        (552, 'Yunxiang', 'zh-CN-shandong-YunxiangNeural', 'Male', 0),
                        (553, 'Yunxi', 'zh-CN-sichuan-YunxiNeural', 'Male', 0),
                        (554, 'HiuMaan', 'zh-HK-HiuMaanNeural', 'Female', 0),
                        (555, 'WanLung', 'zh-HK-WanLungNeural', 'Male', 0),
                        (556, 'HiuGaai', 'zh-HK-HiuGaaiNeural', 'Female', 0),
                        (557, 'HsiaoChen', 'zh-TW-HsiaoChenNeural', 'Female', 0),
                        (558, 'YunJhe', 'zh-TW-YunJheNeural', 'Male', 0),
                        (559, 'HsiaoYu', 'zh-TW-HsiaoYuNeural', 'Female', 0),
                        (560, 'Thando', 'zu-ZA-ThandoNeural', 'Female', 0),
                        (561, 'Themba', 'zu-ZA-ThembaNeural', 'Male', 0);";

        // generate insert from raw_insert
        $voices = array_map('trim', explode("\n", $raw_insert));
        foreach ($voices as $voice) {
            if (empty($voice)) continue;
            
            // Extract values between parentheses
            if (preg_match('/\((.*?)\)/', $voice, $matches)) {
                $values = explode(',', $matches[1]);
                
                // Clean up each value
                $values = array_map(function($val) {
                    return trim(str_replace("'", "", $val));
                }, $values);
    
                if (count($values) >= 5) {
                    DB::table('voices')->insert([
                        'id' => (int)$values[0],
                        'name' => $values[1],
                        'short_name' => $values[2],
                        'gender' => $values[3],
                        'is_favorite' => (int)$values[4],
                    ]);
                }
            }
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('voices');
    }
};
